Homework 4
khomutov-k/KonstantinKhomutov pull request #5
Opened 2020-08-20 12:47 UTC by khomutov-k

Homework 4 is done.

2020-08-23 08:58 UTC, shoggy requested changes

2020-08-23 08:58 UTC, shoggy commented on .gitignore
> +/allure-results/
Could you add `.allure/` please

2020-08-23 08:58 UTC, shoggy commented on pom.xml
> +            </plugin>
This declaration looks redundant because reporting section has its own declaration

2020-08-23 08:58 UTC, shoggy commented on src/test/java/hw4/listeners/AllureAttachmentListener.java
> +    }
the original method is overridden, but it contains useful actions, so would be good to call `super.onTestFailure(tr);` somewhere near

2020-08-23 08:58 UTC, shoggy commented on src/test/java/hw4/listeners/AllureAttachmentListener.java
> +    @Attachment(value = "Attachment: {0}", type = "image/png")
I think you tried to make a good looking name for attachment, but it literally looks like "Attachment: {0}"

Maybe you missed some parameter

2020-08-23 08:58 UTC, shoggy commented on src/test/java/hw4/utils/Helper.java
> +        for (WebElement element : webElements) {
hint:
maybe `org.hamcrest.collection.IsIterableContainingInAnyOrder` could be useful here

2020-08-23 08:58 UTC, shoggy commented on src/test/java/hw4/utils/PropertiesHandler.java
> +public class PropertiesHandler {
maybe `java.util.ResourceBundle` could be useful here

2020-08-23 17:53 UTC, khomutov-k commented on pom.xml
> +            </plugin>
It was made to display Allure plugin in IDE. Is it ok left it like this?

2020-08-24 17:15 UTC, shoggy requested changes
Looks good

2020-08-24 17:15 UTC, shoggy approved these changes

2020-08-25 05:48 UTC, merged